# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true
    AddToolsToPath: true
#- task: PowerPlatformAssignUser@2   
#  displayName: 'Power Platform Assign User'
#  inputs:
#    authenticationType: PowerPlatformSPN
#    PowerPlatformSPN: 'Diplomadossier service connection'
#    User: 3d5952fc-ddd2-4d17-a383-cf1c7dfa5386
#    Role: Systeembeheerder
#    ApplicationUser: true
- task: PowerPlatformExportSolution@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'Diplomadossier service connection'
    SolutionName: 'Diplomadossier'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\DiplomaDossier.zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
